<a href="https://colab.research.google.com/github/niltonmalves/AmazonFineFoodReviews/blob/master/intraday_final.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os

In [0]:
from pandas.plotting import register_matplotlib_converters
register_matplotlib_converters()

In [0]:
path_trade_itsa4='https://raw.githubusercontent.com/niltonmalves/stock/master/itsa4_trade.csv'
pd.read_csv(path_bid_itsa4, sep=';').tail(3)

Dates  Open  Close  High   Low   Value  Volume  Number Ticks
57151  15/05/2020 17:57  8.17   8.16  8.18  8.16  415584   50916            13
57152  15/05/2020 17:58  8.17   8.17  8.18  8.16  823440  100883            19
57153  15/05/2020 17:59  8.17   8.17  8.17  8.17  471989   57771            15

In [0]:
data_trade_itsa4=pd.read_csv(path_trade_itsa4, sep=';').iloc[:,0].values
volume_trade_total_itsa4=pd.read_csv(path_trade_itsa4, sep=';').iloc[:,6].values.astype('float') #volume
valor_trade_total_itsa4=pd.read_csv(path_trade_itsa4, sep=';').iloc[:,5].values.astype('float') #value
media_trade_itsa4=valor_trade_total_itsa4/volume_trade_total_itsa4
media_trade_itsa4[0:2]

array([13.73731066, 13.76205426])

In [0]:
dftrade=pd.DataFrame({'md_trade':media_trade_itsa4,'vlr_trade':valor_trade_total_itsa4},index=data_trade_itsa4)
dftrade.tail(3)

md_trade   vlr_trade
15/05/2020 16:53  8.193766    441644.0
15/05/2020 16:54  8.181014   2461667.0
15/05/2020 17:08  8.140000  28528258.0

In [0]:
## bid intraday itsa4
path_bid_itsa4='https://raw.githubusercontent.com/niltonmalves/stock/master/bid_itsa4_intraday.csv'
pd.read_csv(path_bid_itsa4, sep=';').tail(3)

Dates  Open  Close  High   Low   Value  Volume  Number Ticks
57151  15/05/2020 17:57  8.17   8.16  8.18  8.16  415584   50916            13
57152  15/05/2020 17:58  8.17   8.17  8.18  8.16  823440  100883            19
57153  15/05/2020 17:59  8.17   8.17  8.17  8.17  471989   57771            15

In [0]:
data_bid_itsa4=pd.read_csv(path_bid_itsa4, sep=';').iloc[:,0].values
volume_bid_total_itsa4=pd.read_csv(path_bid_itsa4, sep=';').iloc[:,6].values.astype('float') #volume
valor_bid_total_itsa4=pd.read_csv(path_bid_itsa4, sep=';').iloc[:,5].values.astype('float') #value
media_bid_itsa4=valor_bid_total_itsa4/volume_bid_total_itsa4
media_bid_itsa4[0:2]

array([13.59972678, 14.4596915 ])

In [0]:
dfbid=pd.DataFrame({'md_bid':media_bid_itsa4,'vlr_bid':valor_bid_total_itsa4},index=data_bid_itsa4)
dfbid.tail(3)

md_bid   vlr_bid
15/05/2020 17:57  8.162149  415584.0
15/05/2020 17:58  8.162327  823440.0
15/05/2020 17:59  8.169999  471989.0

In [0]:
dfbid.size

114308

In [0]:
## ask intraday itsa4
path_ask_itsa4='https://raw.githubusercontent.com/niltonmalves/stock/master/ask_itsa4_intraday.csv'

pd.read_csv(path_ask_itsa4, sep=';').tail(3)

Dates  Open  Close  High   Low    Value  Volume  \
57214  15/05/2020 17:57  8.18   8.18  8.19  8.17  1786872  218448   
57215  15/05/2020 17:58  8.17   8.18  8.19  8.17  1146527  140178   
57216  15/05/2020 17:59  8.18   8.18  8.19  8.18  2707658  331009   

       Number Ticks  
57214            32  
57215            25  
57216            24

In [0]:
data_ask_itsa4=pd.read_csv(path_ask_itsa4, sep=';').iloc[:,0].values
volume_ask_total_itsa4=pd.read_csv(path_ask_itsa4, sep=';').iloc[:,6].values.astype('float') #volume
valor_ask_total_itsa4=pd.read_csv(path_ask_itsa4, sep=';').iloc[:,5].values.astype('float') #value
media_ask_itsa4=valor_ask_total_itsa4/volume_ask_total_itsa4
media_ask_itsa4[0:2]

array([13.67277487, 13.59988656])

In [0]:
dfask=pd.DataFrame({'md_ask':media_ask_itsa4,'vlr_ask':valor_ask_total_itsa4},index=data_ask_itsa4)
dfask.tail(3)

md_ask    vlr_ask
15/05/2020 17:57  8.179851  1786872.0
15/05/2020 17:58  8.179079  1146527.0
15/05/2020 17:59  8.180013  2707658.0

In [0]:
dfask.index=pd.to_datetime(dfask.index)
dfbid.index=pd.to_datetime(dfbid.index)

In [0]:
pdmerge=pd.merge(dfbid,dfask, how='inner', on=None, left_on=None, right_on=None,
         left_index=True, right_index=True, sort=False,
         copy=True, indicator=False,
         validate=None) #suffixes=('_x', '_y'), 

pdmerge.head()

md_bid  vlr_bid     md_ask   vlr_ask
2019-11-18 06:08:00  13.599727  19910.0  13.672775    5223.0
2019-11-18 09:45:00  14.459692  99367.0  13.599887  119883.0
2019-11-18 09:59:00   0.043734   1189.0  13.673469    1340.0
2019-11-18 10:00:00   1.387739  12201.0  13.694545    3766.0
2019-11-18 10:01:00   0.195388   3330.0  13.750000    7150.0

In [0]:
pdmerge.columns

Index(['md_bid', 'vlr_bid', 'md_ask', 'vlr_ask'], dtype='object')

In [0]:
pdmerge=pd.merge(pdmerge,dftrade, how='inner', on=None, left_on=None, right_on=None,
         left_index=True, right_index=True, sort=False,
         copy=True, indicator=False,
         validate=None) #suf
pdmerge.head()

md_bid    vlr_bid     md_ask    vlr_ask   md_trade  \
2019-11-18 10:02:00  13.732724  1858834.0  13.750432  5466938.0  13.737311   
2019-11-18 10:03:00  13.752492  5342458.0  13.765032  5638749.0  13.762054   
2019-11-18 10:04:00  13.749413  4434392.0  13.761956  5356745.0  13.755000   
2019-11-18 10:05:00  13.767621  6712445.0  13.780585  4756865.0  13.771784   
2019-11-18 10:06:00  13.756951  8007302.0  13.777118  3788308.0  13.768760   

                     vlr_trade  
2019-11-18 10:02:00   888804.0  
2019-11-18 10:03:00   355061.0  
2019-11-18 10:04:00   277851.0  
2019-11-18 10:05:00   331900.0  
2019-11-18 10:06:00   344219.0

In [0]:
pdmerge.columns

Index(['md_bid', 'vlr_bid', 'md_ask', 'vlr_ask', 'md_trade', 'vlr_trade'], dtype='object')

In [0]:
pdmerge.index

DatetimeIndex(['2019-11-18 06:08:00', '2019-11-18 09:45:00',
               '2019-11-18 09:59:00', '2019-11-18 10:00:00',
               '2019-11-18 10:01:00', '2019-11-18 10:02:00',
               '2019-11-18 10:03:00', '2019-11-18 10:04:00',
               '2019-11-18 10:05:00', '2019-11-18 10:06:00',
               ...
               '2020-05-15 17:50:00', '2020-05-15 17:51:00',
               '2020-05-15 17:52:00', '2020-05-15 17:53:00',
               '2020-05-15 17:54:00', '2020-05-15 17:55:00',
               '2020-05-15 17:56:00', '2020-05-15 17:57:00',
               '2020-05-15 17:58:00', '2020-05-15 17:59:00'],
              dtype='datetime64[ns]', length=56229, freq=None)

In [0]:
#pdmerge.index=pd.to_datetime(pdmerge.index)
#pdmerge=pdmerge.sort_index()
#pdmerge.head()

In [0]:
pdmerge.tail()

md_bid   vlr_bid    md_ask    vlr_ask
2020-05-15 17:55:00  8.163825  698603.0  8.179981  3326144.0
2020-05-15 17:56:00  8.161891  427577.0  8.179985   977001.0
2020-05-15 17:57:00  8.162149  415584.0  8.179851  1786872.0
2020-05-15 17:58:00  8.162327  823440.0  8.179079  1146527.0
2020-05-15 17:59:00  8.169999  471989.0  8.180013  2707658.0

In [0]:
pdmerge.dropna().describe()

md_bid       vlr_bid        md_ask       vlr_ask      md_trade  \
count  52783.000000  5.278300e+04  52783.000000  5.278300e+04  52783.000000   
mean      11.724357  3.923750e+07     11.734844  3.414740e+07     11.755474   
std        2.222703  4.990016e+07      2.226073  3.425049e+07      2.167850   
min        0.004347  1.280000e+03      0.000059  8.500000e+02      7.451111   
25%        9.148850  1.597549e+07      9.159038  1.494406e+07      9.166616   
50%       13.015061  2.748911e+07     13.027277  2.559192e+07     13.025833   
75%       13.494640  4.658175e+07     13.506902  4.211471e+07     13.501378   
max       14.370000  2.696236e+09     14.380000  9.984419e+08     14.375552   

          vlr_trade  
count  5.278300e+04  
mean   6.888868e+05  
std    2.809982e+06  
min    2.691000e+03  
25%    1.767355e+05  
50%    3.547390e+05  
75%    6.795480e+05  
max    2.063458e+08

In [0]:
pdmerge.md_bid.values.shape

(52783,)

In [0]:
pdmerge.md_bid.values


array([13.59972678, 14.4596915 ,  0.04373414, ...,  8.16214942,
        8.16232666,  8.16999879])

In [0]:
#reshape para normalizar
#valor_total_itsa4=np.reshape(valor_total_itsa4,(-1,1))
md_bid_reshaped=np.reshape(pdmerge.md_bid.values,(-1,1))
md_ask_reshaped=np.reshape(pdmerge.md_ask.values,(-1,1))
vlr_ask_reshaped=np.reshape(pdmerge.vlr_ask.values,(-1,1))
vlr_bid_reshaped=np.reshape(pdmerge.vlr_bid.values,(-1,1))

vlr_trade_reshaped=np.reshape(pdmerge.vlr_trade.values,(-1,1))
md_trade_reshaped=np.reshape(pdmerge.md_trade.values,(-1,1))



from sklearn.preprocessing import MinMaxScaler
sc_valor = MinMaxScaler(feature_range = (0, 1))

md_bid_reshaped_scaled = sc_valor.fit_transform(md_bid_reshaped)
md_ask_reshaped_scaled = sc_valor.fit_transform(md_ask_reshaped)
vlr_bid_reshaped_scaled = sc_valor.fit_transform(vlr_bid_reshaped)
vlr_ask_reshaped_scaled = sc_valor.fit_transform(vlr_ask_reshaped)

vlr_trade_reshaped_scaled = sc_valor.fit_transform(vlr_trade_reshaped)
md_trade_reshaped_scaled = sc_valor.fit_transform(md_trade_reshaped)


#valor_total_itsa4_scaled = sc_valor.fit_transform(valor_total_itsa4) 
#print(valor_total_itsa4_scaled.shape)

In [0]:
print(md_bid_reshaped_scaled[0:5])
print(md_ask_reshaped_scaled[0:5])
print(vlr_bid_reshaped_scaled[0:5])
print(vlr_ask_reshaped_scaled[0:5])

[[0.52306641]
 [0.55614198]
 [0.00168208]
 [0.05337457]
 [0.00751493]]
[[0.95081881]
 [0.94575008]
 [0.95086711]
 [0.95233276]
 [0.95618913]]
[[7.38436975e-06]
 [3.68539763e-05]
 [4.40985215e-07]
 [4.52519815e-06]
 [1.23505531e-06]]
[[5.23115055e-06]
 [1.20070079e-04]
 [1.34209109e-06]
 [3.77187689e-06]
 [7.16115766e-06]]


In [0]:
print(md_bid_reshaped_scaled.size)
print(md_ask_reshaped_scaled.size)
print(vlr_bid_reshaped_scaled.size)
print(vlr_ask_reshaped_scaled.size)

52783
52783
52783
52783


In [0]:
window=10
TrainSize=vlr_ask_reshaped_scaled.size
X_train = []
y_train = []
for i in range(window, TrainSize):
    X_train.append(np.array(list(zip(vlr_trade_reshaped_scaled[i-window:i,0],md_trade_reshaped_scaled[i-window:i,0],md_bid_reshaped_scaled[i-window:i,0],md_ask_reshaped_scaled[i-window:i,0],vlr_bid_reshaped_scaled[i-window:i,0],vlr_ask_reshaped_scaled[i-window:i,0]))).flatten())
    y_train.append(md_trade_reshaped_scaled[i,0]) #esta errado, trocar pelo trade

X_train, y_train = np.array(X_train), np.array(y_train)

In [0]:
print(X_train.shape)

(52773, 60)


In [0]:
#Reshaping para usar na rede neural
print(X_train.shape)
print(y_train.shape)
X_train = np.reshape(X_train, (X_train.shape[0], window,6))
print(X_train.shape)

(52773, 10, 6)
(52773,)
(52773, 10, 6)


In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [0]:
### Construção da Rede completa
# Initicializar a RNN
regressor = Sequential()
 
# Adicionar a primeira camada LSTM e Dropout 
#regressor.add(LSTM(units = 100, return_sequences = True, input_shape = (X_train.shape[2], 1)))
regressor.add(LSTM(units = 100, return_sequences = True, input_shape = (window,6)))
regressor.add(Dropout(0.2))
 
# Adicionar a segunda camada LSTM e Dropout
regressor.add(LSTM(units = 80, return_sequences = True))
regressor.add(Dropout(0.2))

# Adicionar a segunda camada LSTM e Dropout
regressor.add(LSTM(units = 60, return_sequences = True))
regressor.add(Dropout(0.2))


# Adicionar a terceira camada LSTM e Dropout
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2))
 
# camada de saída
regressor.add(Dense(units = 1))
 
# Compilar a rede
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')

# Visualizar a rede
regressor.summary()

Model: "sequential_3"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_9 (LSTM)                (None, 10, 100)           42800     
_________________________________________________________________
dropout_9 (Dropout)          (None, 10, 100)           0         
_________________________________________________________________
lstm_10 (LSTM)               (None, 10, 80)            57920     
_________________________________________________________________
dropout_10 (Dropout)         (None, 10, 80)            0         
_________________________________________________________________
lstm_11 (LSTM)               (None, 10, 60)            33840     
_________________________________________________________________
dropout_11 (Dropout)         (None, 10, 60)            0         
_________________________________________________________________
lstm_12 (LSTM)               (None, 50)               

In [0]:
#Treinamento
regressor.fit(X_train, y_train, epochs = 5, batch_size = 32)

Epoch 1/5
52773/52773 [==============================] - 72s 1ms/step - loss: 0.0051
Epoch 2/5
52773/52773 [==============================] - 66s 1ms/step - loss: 0.0018
Epoch 3/5
41248/52773 [======================>.......] - ETA: 13s - loss: 0.0012

KeyboardInterrupt: 

In [0]:
#np.array(list(zip(a,b))).flatten()

In [0]:
#
import seaborn as sns
plt.subplots(figsize=(10,5))
plt.subplot(211)
sns.distplot(pdmerge['md_bid'].dropna(), bins=50, color='purple')
plt.subplot(212)
sns.distplot(pdmerge['md_ask'].dropna(), bins=50, color='blue')
plt.show();

In [0]:
plt.subplots(figsize=(10,5))
plt.subplot(211)
sns.distplot(pdmerge['vlr_bid'].dropna(), bins=50, color='purple')
plt.subplot(212)
sns.distplot(pdmerge['vlr_ask'].dropna(), bins=50, color='blue')
plt.show();

In [0]:
import matplotlib as mpl
import matplotlib.pyplot as plt

plt.style.use('ggplot')
import pandas as pd
import numpy as np
from datetime imporfigsize=(15,8)t datetime

fig, ax = plt.subplots(nrows=2, sharex=True, figsize=(15,8))

ax[0].plot(pdmerge.index[400:570], pdmerge.md_bid[400:570])
ax[1].bar(pdmerge.index[400:570], pdmerge.vlr_bid[400:570], width=1/(5*len(pdmerge.index)))

xfmt = mpl.dates.DateFormatter('%H:%M')
ax[1].xaxis.set_major_locator(mpl.dates.HourLocator(interval=3))
ax[1].xaxis.set_major_formatter(xfmt)

ax[1].xaxis.set_minor_locator(mpl.dates.HourLocator(interval=1))
ax[1].xaxis.set_minor_formatter(xfmt)

ax[1].get_xaxis().set_tick_params(which='major', pad=25)

fig.autofmt_xdate()
plt.show();



In [0]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_datareader.data as web
from datetime import datetime
%matplotlib inline

In [0]:
end = datetime.now()
start = datetime(end.year-2, end.month, end.day)
 
CMT = web.DataReader("ITSA4.SA", 'yahoo', start, end)
CMT.head(2)

In [0]:
CMT['Adj Close'].plot(legend=True, figsize=(10, 5), \
title='CapitaMall Trust', \
label='Adjusted Closing Price')

In [0]:
plt.figure(figsize=(10,5))
top = plt.subplot2grid((4,4), (0, 0), rowspan=3, colspan=4)
bottom = plt.subplot2grid((4,4), (3,0), rowspan=1, colspan=4)
top.plot(CMT.index, CMT['Adj Close']) #CMT.index gives the dates
bottom.bar(CMT.index, CMT['Volume']) 
 
# set the labels
top.axes.get_xaxis().set_visible(False)
top.set_title('CapitalMall Trust')
top.set_ylabel('Adj Closing Price')
bottom.set_ylabel('Volume')

In [0]:
plt.figure(figsize=(10,5))
sns.distplot(CMT['Adj Close'].dropna(), bins=50, color='purple')


In [0]:
sns.distplot(pdmerge['md_bid'].dropna(), bins=50, color='purple')

In [0]:
# simple moving averages
sma10 = CMT['Close'].rolling(10).mean() #10 days
sma20 = CMT['Close'].rolling(20).mean() #20 days
sma50 = CMT['Close'].rolling(50).mean() #50 days
 
CMTsma = pd.DataFrame({'CMT': CMT['Close'], 'SMA 10': sma10, 'SMA 20': sma20, 'SMA 50': sma50})
CMTsma.plot(figsize=(10,5), legend=True, title='CapitaMall Trust')
 
# add vertical lines with annotations
plt.axvline(x = '2015-11-3', color = "black", lw=0.5)
plt.text('2015-10-23', 2.25, 'SMA 10-20',rotation=90)
plt.axvline(x = '2015-11-20', color = "black", lw=0.5)
plt.text('2015-11-24', 2.25, 'SMA 10-50',rotation=90)

In [0]:
dfask.size

In [0]:
print(data_ask_itsa4.size)
print(data_bid_itsa4.size)

In [0]:
type(data_ask_itsa4[0])

In [0]:
data_ask_itsa4[0]

In [0]:
#from datetime import datetime
#datetime_str = data_ask_itsa4[0]

#datetime_object = datetime.strptime(datetime_str, '%d/%m/%Y %H:%M')

#print(type(datetime_object))
#print(datetime_object)  # printed in default format

In [0]:
#date_index=[]
#for i in range(data_ask_itsa4.size):
    
#    datetime_str = data_ask_itsa4[i]

#    datetime_object = datetime.strptime(datetime_str, '%d/%m/%Y %H:%M')
#    date_index.append(datetime_object)

  #  print(type(datetime_object))
  #  print(datetime_object)  # printed in default format


In [0]:
#for j in range(data_bid_itsa4.size):
    
#    datetime_str = data_bid_itsa4[j]

#    datetime_object = datetime.strptime(datetime_str, '%d/%m/%Y %H:%M')
#    date_index.append(datetime_object)
    

In [0]:
#a=sorted(date_index)
#a=set(a)
#a=sorted(a)
#date_index=np.array(a)
#t=pd.DataFrame(index=date_index)
#l=[t,dfask]
#pd.concat(l,axis=1).reindex(t.index)